### PR TITLE
Build on nix systems

### PR DESCRIPTION
**Pull request by kalinowskitomasz**
I've reduced changes only to cmakelists and enabling build on *nix. Malloc test is failing. I haven't really tested 32 bit version, MacOS is deprecating i386 and while you can still build binary, some system libraries were removed and XCode will not work with them.

### CODE REVIEW

**Comment by stevemk14ebr** [comment]
Can you explain how this bit works please, my cmake isn't up to par:

```
target_compile_options(PolyHook_2 PUBLIC "$<$<CONFIG:DEBUG>:${MY_DEBUG_OPTIONS}>")
target_compile_options(PolyHook_2 PUBLIC "$<$<CONFIG:RELEASE>:${MY_DEBUG_OPTIONS}>")
```

And also when loading the project in Visual Studio 2017 (with the cmake plugin) the build target is parsed by reading CMakeSettings.json, do you think this now needs updated as well?

**Comment by stevemk14ebr** [comment]
This breaks the windows build, i have to revert. Please fix the memory protector to respect windows flags too. Additionally the testrunner doesn't properly link to the polyhook dll, there is a libcmt conflict

**Comment by kalinowskitomasz** [comment]
I’ll check it today. There is Azure Pipelines CI that offers free windows, linux mac builds. I had a look at it and it seems to be fairly easy to set up.

**Comment by stevemk14ebr** [comment]
That would be very beneficial

**Pull request merged**
