### PR TITLE
Fixed erroneous asmjit revision.

### PR DESCRIPTION
**Pull request by gir489**
When trying to pull the project recursively, an error occurs with the asmjit project because that commit no longer exists.

### CODE REVIEW

**Comment by stevemk14ebr** [comment]
This is because he merged that branch to master recently. Appreciated!

**Comment by gir489** [comment]
Wow that was fast. 😍

**Comment by stevemk14ebr** [comment]
Can you do this for the other branch I've got too?

**Comment by gir489** [comment]
Done.

**Pull request merged**
