### PR TITLE
[WIP] RIP-relative translation

### PR DESCRIPTION
**Pull request by acidicoala**
This work-in-progress PR aims bring implementation of RIP-relative instruction translation in accordance with the issue #119. At the moment it covers only a single special case of `cmp [RIP+offset], <immediate>`, so that it passes the *SetProcessDPIAware* unit test committed earlier. The purpose of opening this PR is to receive critical feedback from the library author @stevemk14ebr so that every possible caveat is taken into account. This PR will be receiving many commits iteratively improving the implementation.

Below you can find the log of a successful translation operation:

<details><summary>Click to view the log</summary>

```
[+] Info: Original function:
7ffb1876b4c0 [7]: 83 3d a5 7e 09 00 00          cmp dword ptr ds:[0x00007FFB1880336C], 0x00 -> 7ffb1880336c
7ffb1876b4c7 [6]: 0f 85 d9 68 02 00             jnz 0x00007FFB18791DA6 -> 7ffb18791da6
7ffb1876b4cd [7]: 48 c7 c1 fe ff ff ff          mov rcx, 0xFFFFFFFFFFFFFFFE
7ffb1876b4d4 [5]: e9 07 f0 ff ff                jmp 0x00007FFB1876A4E0 -> 7ffb1876a4e0


[+] Info: Prologue to overwrite:
7ffb1876b4c0 [7]: 83 3d a5 7e 09 00 00          cmp dword ptr ds:[0x00007FFB1880336C], 0x00 -> 7ffb1880336c


[!] Warn: Cannot fixup IP relative data operation, needed disp. beyond max disp range: cmp dword ptr ds:[0x00007FFB18803
36C], 0x00 needed: 0x00007ea40e995d00 raw: 0xffff815bf166a300 max: 0x000000007fffffff
[+] Info: Translation:
15709df2cb0 [8]: 48 8d a4 24 d8 fe ff ff       lea rsp, ss:[rsp-0x128]
15709df2cb8 [1]: 50                            push rax
15709df2cb9 [a]: 48 b8 6c 33 80 18 fb 7f 00 00 mov rax, 0x00007ffb1880336c
15709df2cc3 [6]: 48 3d 00 00 00 00             cmp rax, 0x0000000000000000
15709df2cc9 [1]: 58                            pop rax
15709df2cca [8]: 48 8d a4 24 28 01 00 00       lea rsp, ss:[rsp+0x128]
15709df2cd2 [5]: e9 f0 2a fe ff                jmp 15709dd57c7


[+] Info: Jmp To Prol:
15709dd57c7 [6]: ff 25 4b 00 00 00             jmp [15709dd5818] ->7ffb1876b4c7
15709dd5818 [8]: c7 b4 76 18 fb 7f 00 00       dest holder


[+] Info: Trampoline:
15709dd57c0 [5]: e9 eb d4 01 00                jmp 0x0000015709DF2CB0 -> 15709df2cb0
15709dd57c5 [1]: 90                            nop nop
15709dd57c6 [1]: 90                            nop nop
```
</details>

### CODE REVIEW

**Comment by stevemk14ebr** [comment]
This is really great thanks so much! I will review in depth soon and hopefully we can merge this!

**Comment by acidicoala** [comment]
>  hopefully we can merge this!

Eventually yes, but definitely not in its current state :) As the name suggests, it's still a WIP.

**Comment by acidicoala** [comment]
The latest commit warrants some explanation.

I have switched to using `asmjit` for generation of the translation routine. More specifically, [asmtk](https://github.com/asmjit/asmtk) is used for parsing of assembly strings. Since `asmtk` is not ported to vcpkg, it remains to be seen if the project will now build correctly. The latest asmtk required latest asmjit, which had some backward incompatible changes that affected `ILCallback`. I *think* I've fixed them correctly, at least according to the unit tests. I can't say for sure since I've got no idea what's this all about.

I created a new test source file `TestDetourRelativex64` which will contain test cases only dealing with RIP-relative data operations. This makes it more organized imo, than mixing it all in `TestDetourx64`. The tests themselves use hand-written assembly instructions for consistency, just like some tests in the `TestDetourx64`.

The `Instruction` class now has a register member field, which is used to avoid collisions when picking scratch register during translation. Essentially, the scratch register will be rax/eax/ax/al unless either of them are used, in which case scratch register will be rbx/ebx/bx/bl.

In some files, I let my IDE format the code, as formatting it manually according to the existing conventions was too cumbersome. This resulted in a bunch of spacing/indentation changes which may not conform to your preferred style. Let us address this once the feature has been fully completed. Ideally, there should be a config file in the repository which defines all formatting rules. `.editorconfig` or `.clang-tidy` would be good options imo.

**The main problem** facing us right now is the allocation of translation routine beyond the 2gb offset of the trampoline. The allocation is done by asmjit at the moment and it fails during relocation. Interestingly enough, it fails only when displacement is a `dword` pointer. `qword`, `word`, and `byte` pointers strangely enough, don't usually fail. To solve this issue, I'm thinking of changing 2 things:
- Instead of relative jump from trampoline to translation we add the jump to trampoline as an entry below the trampoline, which is already done for `call/jmp` instructions, if I understand correctly.
- Instead of relative jump from translation to trampoline we add a `mov rax, <dest>` + `jmp rax` at the bottom of translation.

Looking forward to hearing your thoughts on this approach.

**Comment by stevemk14ebr** [comment]
Hey neat technique using asmtk! I haven't had time to manage this just yet, but I read some of the code and your comment. One thing that sticks out is this:

> The main problem facing us right now is the allocation of translation routine beyond the 2gb offset of the trampoline

I believe what we can do is to expand the trampoline, and put the translation routines at the very end. This way they're always really close to the trampoline code that needs to be translated. With this I don't think we'll have any issues with distance?

> Instead of relative jump from trampoline to translation we add an indirect jump as an entry below the trampoline, which is already done for call/jmp instructions, if I understand correctly

With the above change I think this goes away, but using the mov reg trick is totally fine, but we would have to take care rax isn't used already by something, so you'd probably need another reg pass. Easier to avoid this if possible



The red zone is also 128 bytes, so use decimal instead of hex for those.

**Comment by acidicoala** [comment]
> I believe what we can do is to expand the trampoline
I also thought about this, but won't it make more difficult to find a nearby code cave or make an in-place detour? The translation routine is bigger than the usual trampoline and there may be more than one of them, if the trampoline includes more than 1 IP-relative data operation. Doesn't that increased size decrease probability of finding a suitable code cave, as well as decrease chances of fitting the trampoline+translation into function prologue?

**Comment by stevemk14ebr** [comment]
It definitely does hurt our chances of a successful allocation. Thinking about it more, is it possible we can get away with putting the translation stubs anywhere, then we can just use normal allocation routines and not worry about distances. I think since we control the translation stubs and the trampoline we can do this, we'd put a jump address entry at the end of the trampoline, this would hold the full 64bit address of where the translation stub gets allocated, and the address would always be +- 2GB since its just at the end of the trampoline. To jump to the stub we'd then use https://github.com/stevemk14ebr/PolyHook_2_0/blob/ce93f6fa9fc8d324e9411ad8d823c7315ea4b57b/polyhook2/Instruction.hpp#L370, and to jump back use the mov reg, jmp or we could probably even use this: https://github.com/stevemk14ebr/PolyHook_2_0/blob/ce93f6fa9fc8d324e9411ad8d823c7315ea4b57b/polyhook2/Instruction.hpp#L325 which doesn't spoil anything

**Comment by acidicoala** [comment]
> I think since we control the translation stubs and the trampoline we can do this, we'd put a jump address entry at the end of the trampoline, this would hold the full 64bit address of where the translation stub gets allocated, and the address would always be +- 2GB since its just at the end of the trampoline.

Isn't this the same approach I proposed in my initial comment? 🙂

> * Instead of relative jump from trampoline to translation we add an indirect jump as an entry below the trampoline, which is already done for call/jmp instructions, if I understand correctly.
> * Instead of relative jump from translation to trampoline we add a mov rax, <dest> + jmp rax at the bottom of translation.

Only in this case we use the pristine `makex64PreferredJump` instead of the my dirty, rax-spoiling approach. I like the sound of this approach much more, so will try it out.
___
> If we did end up allocating our own memory and want asmjit to use it

In this case, can't we just provide a base address to asmjit during [init](https://asmjit.com/doc/classasmjit_1_1CodeHolder.html#ac2f38947fb14ceb1f0a478c03fdcf1d8) of `CodeHolder`?
___
> It's like dynamically creating a callback stub to hook things at runtime when you don't know their call signature until after compilation

Hmm, what is the use case of such feature? If I understand correctly, you don't need to know call signature of any native function for hooking it, isn't it? We need to know it only when calling the original function. So if I understand correctly, this feature allows us to *call* the original function without knowing its signature?

**Comment by stevemk14ebr** [comment]
> In this case, can't we just provide a base address to asmjit during [init](https://asmjit.com/doc/classasmjit_1_1CodeHolder.html#ac2f38947fb14ceb1f0a478c03fdcf1d8) of CodeHolder?

When I wrote that code you could get asmjit to write to memory assuming instructions were at some memory location, but it would not let you allocate your own memory and write to it. My way lets you control the code entirely, not sure if needed, but it works that way.

> Hmm, what is the use case of such feature? If I understand correctly, you don't need to know call signature of any native function for hooking it, isn't it? We need to know it only when calling the original function. So if I understand correctly, this feature allows us to call the original function without knowing its signature?

For runtime tracing really. You can have external binaries and you want to be able to log function arguments and such, so you at runtime provide a function name and typedef, then you can print out the arguments. It lets you dynamically create the callback stubs. And yes it can also be used to call funtions at runtime, with some modifications, I do that here: https://github.com/stevemk14ebr/RETools/tree/master/JITCall

> Isn't this the same approach I proposed in my initial comment? 🙂

It might be, If so then lets do that!

**Comment by acidicoala** [comment]
The latest commit implements the above-mentioned approach, and it passes all tests that involve RIP-relative data operations *with registers*. In the process I discovered that in translation routine we cannot directly encode `mov %scratch_register%, ptr ds:[%64_bit_dest_address%]`, hence it was split into 2 instructions: `mov %address_register%, %64_bit_dest_address%` && `mov %scratch_register%, [%address_register%]`.

All that is left now is to implement support for instructions with immediate values, and refactor.

**Comment by stevemk14ebr** [comment]
Thanks for working on this so much! Some little things, I don't think that this is hacky at all, it's clever actually. The creation of the instruction should be refactored to a standalone function though:

```
// This is a somewhat hacky solution. We store the absolute address,
		// but set the instruction as relative to fit into the existing entry-table logic
		Instruction::Displacement disp{};
		disp.Absolute = translation_address;
		*inst_iterator = Instruction(instruction.getAddress(), disp, 1, true, false, {0xE9, 0, 0, 0, 0}, "jmp", PLH::int_to_hex(translation_address), Mode::x64);
		inst_iterator->setHasDisplacement(true);
		instsNeedingEntry.push_back(*inst_iterator);
		instsNeedingAbsJmps.push_back(*inst_iterator);
```

Generally using asmtk is totally fine for dev. When this branch is finalized we should remove that dependancy and build the PLH::Instruction objects ourselves. I believe that theres few enough instructions that this is reasonable, if I'm wrong let me know. This is the very last step before merge though, no need to do it now until we finish this PR. 

I've also changed this:
```
lea rsp, [rsp - 0x80]
push rax
push r15
mov r15, 0x00007ff6359440c0
mov rax, [r15]
cmp rax, r10
pop r15
pop rax
lea rsp, [rsp + 0x80]
push rax
mov rax, 0x000001db0861e287
xchg [rsp], rax
ret
```

into this

```
lea rsp, [rsp - 0x80]
push rax
push r15
mov r15, 0x00007ff6359440c0
mov rax, [r15]
cmp rax, r10
pop r15
pop rax
push rax
mov rax, 0x000001db0861e287
xchg [rsp], rax
ret 0x0080
```

This is because the push rax at the end would end up writing to rsp-8 after we fixup rsp and that memory is within the redzone. By using the ret to cleanup our little return address gets written to free stack space then we reset rsp after that. Little thing but the order matters to not clobber red zone.

**Comment by acidicoala** [comment]
> Generally using asmtk is totally fine for dev. When this branch is finalized we should remove that dependancy and build the PLH::Instruction objects ourselves. I believe that theres few enough instructions that this is reasonable, if I'm wrong let me know. Unfortunately vcpkg is somewhat important to us since this is a CMAKE project and it's easier to consume via vcpkg for 99% of our users - some of my own tools do it this way too :/ . This is the very last step before merge though, no need to do it now until we finish this PR.

Building instructions on our is going to require us to implement mini assembler for encoding REX prefix, opcode, ModRM, and SIB bytes. I cannot imagine the amount of work for that. If you want to avoid AsmTK, it is possible to assemble instructions using AsmJIT, but that would require a whole lot of if-else branches for each instruction, because of all possible registers that might be used in instructions. Very dirty, and cumbersome. If it is important for you to have a representation of translation routine in internal model (`PLH::insts_t`), then we can just parse the generated routine with Zydis. If the vcpkg port is important (which it is to me) then I can submit an AsmTK port - it wouldn't be as crazy as implementing this feature. In the worst case scenario, if we fail to port AsmTK, we can just modify the setup script to download the repo and unpack it in the PH2 root.

> And finally, please don't use C++ exceptions or try catch. I prefer to use either std::optional when appropriate for conditionally successful values, or just a bool return type to indicate success failure, either is fine.

I used them because I found it quicker to use during development. I can remove it all during refactoring. May I ask why you avoid them?

> I've also changed this (see https://github.com/acidicoala/PolyHook_2_0/pull/1 to merge my changed into this PR):

Thanks, merged.

**Comment by stevemk14ebr** [comment]
> If it is important for you to have a representation of translation routine in internal model (PLH::insts_t), then we can just parse the generated routine with Zydis

This is not a priority for me. All I care about is having the vcpkg port working, so putting asmtk on vcpkg would work fine. I understand about the encodings, I may have underestimated the amount of work, I had assumed there'd be few variants but if this is not true then we'll keep asmtk!

> I can remove it all during refactoring. May I ask why you avoid them?

yes please. Exceptions require some low level machinery in the binary to work and that complicates injecting into other binaries and loading dlls manually. They're also not needed here, so better to avoid that incidental complexity. In general I hate exceptions, they're a bad form of control flow and I think C++ should not use them. Rust's style of Option and Result is much better, type safe, and declaritive. C++'s std::optional is the best middle ground without rolling our own stuff, or using just bool return types.

**Comment by acidicoala** [comment]
The latest commit adds support for RIP-relative data operations with immediate operands. It also adds support for operand order in operations with register, i.e. `cmp rax, [0x...]` and `cmp [0x...], rax`.

**Comment by stevemk14ebr** [comment]
Awesome work again!

**Comment by acidicoala** [comment]
Is there anything left to cover, or should we begin refactoring?

**Comment by stevemk14ebr** [comment]
lets move forward with the refactor, remove those exceptions then we'll get asmtk ported and we can merge with additional testing. 

> In the process I discovered that in translation routine we cannot directly encode mov %scratch_register%, ptr ds:[%64_bit_dest_address%], hence it was split into 2 instructions: mov %address_register%, %64_bit_dest_address% && mov %scratch_register%, [%address_register%]

This is what the instructions_to_store variable is for right? Can we comment this better if so?

**Comment by acidicoala** [comment]
> This is what the instructions_to_store variable is for right? Can we comment this better if so?
No, this is what `address_register_string` variable is for.

`instructions_to_store` holds a list of instructions that require us to store contents of the scratch register into the original destination address. For example, in `add [0x...], rbx` after translation we also need to store it: `add rax, rbx` && `mov [r15], rax`, where as in `cmp` instruction for instance there is no such requirement.

Apart from the main refactoring, can we address the issue of the formatting? My IDE (CLion) constantly formats code in a manner that is not in alignment with current style. If you have a configured style, could you export it? I see that you have `.idea` folder in exclusion, but this prevents developers from sharing formatting styles, inspection configuration, and other settings that ought to be synchronized. The `.idea` folder usually contains its own `.gitignore` which lists files and folders that really need to be excluded from VCS.

**Comment by acidicoala** [comment]
In the mean time I wanted to test this branch with a real project of mine. In the process I needed to port `asmtk`, but I'm having trouble linking it with asmjit. AsmTK provides `ASMJIT_EMBED` and `ASMTK_EMBED` to configure CMake, but I'm confused about how to properly set them up. It also includes AsmJIT's CMake file: https://github.com/asmjit/asmtk/blob/53b251c50676380d3bbd24df6c3217037e193592/CMakeLists.txt#L101. Not sure if it should be patched away or left. The main problem is that it doesn't find AsmJIT target even though I have added it as a dependency. Any ideas how to properly link them?
<details><summary>vcpkg/ports/asmtk/portfile.cmake</summary>

```cmake
vcpkg_from_github(
  OUT_SOURCE_PATH SOURCE_PATH
  REPO asmjit/asmtk
  REF 53b251c50676380d3bbd24df6c3217037e193592 # accessed on 2021-12-14
  SHA512 dc487b82d4a42b030a4b60e0f04281cc07f55521e37c38a6cfdb5126adaa888652de40a242e9641350bb5f37df57b639686d87ca11c89cf420845890c0244814
  HEAD_REF master
#  PATCHES
#      do_not_include_asmjiit.patch
)


string(COMPARE EQUAL "${VCPKG_LIBRARY_LINKAGE}" "static" ASMTK_STATIC)

#find_package(AsmJit CONFIG REQUIRED)
#set(ASMJIT_EMBED FALSE)

#find_package(asmjit CONFIG REQUIRED)
message(WARNING "AsmJIT DIR: ${ASMJIT_DIR}")

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        -DASMTK_STATIC=${ASMTK_STATIC}
)

vcpkg_cmake_install()
vcpkg_copy_pdbs()

vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/asmtk)

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")

if(VCPKG_LIBRARY_LINKAGE STREQUAL "static")
    vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/include/asmtk/globals.h"
        "#if !defined(ASMTK_STATIC)"
        "#if 0"
    )
endif()

file(INSTALL "${SOURCE_PATH}/LICENSE.md" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```
</details>

<details><summary>vcpkg/ports/asmtk/vcpkg.json</summary>

```json
{
  "name": "asmtk",
  "version-date": "2021-12-14",
  "port-version": 0,
  "description": "Assembler toolkit based on AsmJit",
  "homepage": "https://github.com/asmjit/asmtk",
  "supports": "!arm",
  "dependencies": [
    "asmjit",
    {
      "name": "vcpkg-cmake",
      "host": true
    },
    {
      "name": "vcpkg-cmake-config",
      "host": true
    }
  ]
}
```
</details>

**Comment by stevemk14ebr** [comment]
Ok I understand `instructions_to_store` now, thanks! 

> Should we remove those unnecessary parameters

Yea lets do it, sounds reasonable

> I don't think it simplifies API in a meaningful way. I strive towards keeping the codebase lean, so I propose to keep just one constructor. What if we made the address and fn_callback generic parameters? PLH would convert them to whatever type is necessary. In the future, with C++20 concepts we could improve compile-time type-safety of generics. Furthermore, I don't mind providing public helpers for casting

This is acceptable to me. I'd personally prefer the uint64_t if we keep just one, it's more obvious the users should provide a VA address with that style. Making them generic would be fine too, I am ok with bumping this project to C++ 20 as well, if you wanted to try the concepts route. Just note that if you do and I'll update the readmes and project info.

> The const qualifiers for primitive parameters in function declarations (Detour constructors for instance) also still bug me. We will of course mark the parameter as const in definition, which would prevent accidental writes. But for users calling the function, it doesn't matter if it's const or not, because primitives values are going to be copied. For me it's like qualifying water as wet

True, these are not necessary. I don't feel super strongly either way, if it really bothers you feel free to remove all of them in the declarations. Just keep the style uniform is all I ask. My personal style I like these, but yea, subjective. If you'd like to upload your formatting configs that's fine, I don't use any anymore. I've switched editors multiple times during this project so it's a bit different in some places. The only rule I have is that brackets go around if's always, and the braces are on the same line as the if, or class, or function declaration like here: https://github.com/stevemk14ebr/PolyHook_2_0/blob/750e78f8d7ebfc291e1c0dce3a0763c3a4b86737/polyhook2/Detour/ADetour.hpp#L150-L158. You can delete my .idea folder for this.

> Unfortunately I couldn't reuse writeNop because it writes directly to memory

Can writeNop be replaced by your version? And the call sites updated to just commit the instructions immediately. Would rather not have two of these. If not, I can take a pass at this later to clean it up. 

Thanks for you refactors! I'll try to take a stab at the asmtk stuff. You probably do not want to be using the _EMBED flags, these were made by the author so that you can directly copy and paste the headers and cpp files into your own project and it disabled the function exports that would normally be used for linking. We probably want to use the linking setup (no _EMBED flags), and ideally, static linking so users don't need to carry around the .dlls for those.

**Comment by acidicoala** [comment]
> Making them generic would be fine too, I am ok with bumping this project to C++ 20 as well, if you wanted to try the concepts route.

Personally, I would love to go c++ 20, because it has std lib improvements such as `.contains` method on sets and maps. We could replace some vectors with sets and use that method for O(1) access time in sets, instead of O(n) via `std::find` in vectors. But I am concerned that others might find it objectionable because they are limited to C++ 17 for whatever reason. I think Polyhook would benefit from semantic versioning, so that the compatibility contract is clear and consumers know what to expect when major/minor/patch version changes. This update for example would be a major update, allowing to us introduce breaking changes. For now I will have a look at C++ 20 concepts to see if they improve the API.

> The only rule I have is that brackets go around if's always,

I'm not sure I follow this. Could you please provide an example?

> and the braces are on the same line as the if, or class, or function declaration

I got this, i.e. no breaks before braces.

> Can writeNop be replaced by your version? 

Sure, can do.

> I'll try to take a stab at the asmtk stuff.

That would be *really*, **really**, **_really_** awesome, because I'm quite inept at this whole vcpkg + Cmake integration. I find the vcpkg documentation to be lackluster, to say the least.

**Comment by acidicoala** [comment]
Latest commit contains formatted `x64Detour` class. Let me know if there is something bothering you in this new style, because my IDE will apply it everywhere.

**Comment by acidicoala** [comment]
Latest commit includes refactors of Detour class and its descendants. Constructors now require only the bare minimum:
```cpp
x64Detour(const uint64_t fnAddress, const uint64_t fnCallback, uint64_t* userTrampVar);
```
The `maxDepth` is now modifiable via setter and accessible via getter. This make it more consistent with other configurable members, such as `detourScheme`.

In the process of reformatting I went through line by line, and fixed some warnings, like implicit double to float conversion.

**Comment by stevemk14ebr** [comment]
> But I am concerned that others might find it objectionable because they are limited to C++ 17 for whatever reason

I've never shyed from breaking changes. This is fine for me, this library will always be 'modern'. I am not concerned with this, but lets not get side tracked, we can do these other changes in a later PR if need be.

> The only rule I have is that brackets go around if's always,
I'm not sure I follow this. Could you please provide an example?

Prefer always putting brackets around if statements, always put brackets around the if. This is bad to me:
```
if(!condition)
    continue;
```
I'll admit I break my own preference sometimes, braces are preferred though.

The new format looks good!

> The maxDepth is now modifiable via setter and accessible via getter. This make it more consistent with other configurable members, such as detourScheme. In the process of reformatting I went through the code line by line and fixed some warnings, like implicit double to float conversion.

Thanks!

> By the way, we would probably also want to modify polyhook's port in vcpkg to remove capstone and zydis features, and make zydis a dependency of detours feature, right?

Yes

> I'm still struggling to port asmtk. It's confusing because in Polyhook itself conditionally imports AsmJit. Now it has to conditionally import AsmTk as well, but should it in this case import AsmJit as well, or let AsmTk transitively import it? AsmTK directly includes AsmJit's CMakeLists.txt, but I don't know if this should always be the case or only when using when a certain flag is set, like ASMJIT_EXTERNAL

Let me try to do this. I am not good at vcpkg at all either, but I do understand the linking at least. We'd want polyhook to still link to asmjit, then we'd also link to asmtk - which itself would link to asmjit again. The linker will resolve the transitive symbols itself, we link ourselves to asmjit tell the linker we depend on symbols it export it doesn't matter to it if additional libraries we use also require those same symbols - that lib will specificy its own dependencies

**Comment by acidicoala** [comment]
>
```
if(!condition)
    continue;
```
Oh, I get it now. Yes, I also add braces when they are missing. The misplaced indentation can lead to easy-to-overlook bugs.


> Alternatively we could probably use the same jump sequence we used earlier, only down side it's alot longer than the existing one (over double)

What if we had 2 in-place schemes. One is the longer one, but which doesn't spoil anything, the other being the existing one. First the longer is one is tried, and if it fails, we fallback to the spoiling but short one?

**Comment by stevemk14ebr** [comment]
> The misplaced indentation can lead to easy-to-overlook bugs

exactly, you get it

> What if we had 2 in-place schemes. One is the longer one, but which doesn't spoil anything, the other being the existing one. First the longer is one is tried, and if it fails, we fallback to the spoiling but short one? Also, why is in-place scheme excluded from recommended? Isn't it worth trying out rather than failing by default?

that'd be great! Prefer the longer unless not enough space. And it's not recommended because it spoils registers, I want people to opt into that themselves. In the lack of proper documentation that was my way of saying don't use this unless you have to

**Comment by acidicoala** [comment]
I see. So with this new non-spoiling scheme, can we make the recommended as valloc | in-place (no-spoil) | code-cave?

**Comment by stevemk14ebr** [comment]
yea that's a new good order! 

I also created https://github.com/microsoft/vcpkg/issues/24359 to help with the port. I am not sure why but I am getting portfile install errors when cmake tries to execute it's own routines such as:
```
-- Using source at C:/Users/steve/source/repos/vcpkg/buildtrees/asmtk/src/037e193592-a000a36f17.clean
CMake Error at ports/asmtk/portfile.cmake:13 (vcpkg_cmake_configure):
  Unknown CMake command "vcpkg_cmake_configure".
Call Stack (most recent call first):
  scripts/ports.cmake:145 (include)
```

**Comment by acidicoala** [comment]
I've had *a bit* of progress when using modified CMakeLists.txt in asmtk: https://github.com/acidicoala/asmtk. Whatever changes we make here, we can submit to upstream, or make a patch file if that fails.

Now it fails at `vcpkg_cmake_install` command, with the following error: `ninja: error: unknown target 'install'`. Weird stuff.

<details><summary>ports/asmtk/portfile.cmake</summary>

```cmake
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO acidicoala/asmtk
    REF fc2bf882d7750bdf3063f2dadc59d5751c361146 # accessed on 2021-12-14
    SHA512 540e6c1d9137f8070071a65b6d0b8aee136cdbe3fbe63b7828dad782145a4916a83b87703ff80d33c98776c86ace9393b8bd181e913106859e3c0b1b08fb06d5
    HEAD_REF master
)

string(COMPARE EQUAL "${VCPKG_LIBRARY_LINKAGE}" "static" ASMTK_STATIC)

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
    -DASMTK_STATIC=${ASMTK_STATIC}
    -DASMJIT_EXTERNAL=TRUE
)

vcpkg_cmake_install()
vcpkg_copy_pdbs()

vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/asmtk)

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")

if (VCPKG_LIBRARY_LINKAGE STREQUAL "static")
    vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/include/asmtk/globals.h"
        "#if !defined(ASMTK_STATIC)"
        "#if 0"
        )
endif ()

file(INSTALL "${SOURCE_PATH}/LICENSE.md" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```
</details>

**Comment by acidicoala** [comment]
* Pending vcpkg asmjit update here: https://github.com/microsoft/vcpkg/pull/24362
* Pending asmtk vcpkg support here: https://github.com/asmjit/asmtk/pull/26. After that, will submit an asmtk port to vcpkg.

**Comment by stevemk14ebr** [comment]
Thanks for your continued work on this! Unfortunate we need to touch so many things to get this done, but I think we're close! We'll have to see how the vcpkg folks want to handle polyhook2 failing now, I'd be open to merging this early, then pushing a vcpkg port update at the same time, with the caveat that it depends on asmtk and asmjit ports to be approved as well. They probably have a process for cyclic dependency breakage like this

**Comment by acidicoala** [comment]
Yes, I am curious to see how they resolve this. Apart from this, is there anything left to refactor for this PR? I'm cool with merging it now and adding c++ 20 support later. This PR is already big enough.

**Comment by stevemk14ebr** [comment]
The only things I can think of are optional, feel free to ignore or do a later PR, but I'd accept them in this PR if you do it. The new in place scheme is one item, then changing the preferred enum to include it in the order we discussed. And optional additional tests if you think any are relevant.

I'm happy with the current PR, it works, and we can merge first and let bugs fall out later through testing or community reports of issues. Unit tests give us a good first pass.

**Comment by acidicoala** [comment]
Yes, I think the new detour scheme can be added in a separate, focused PR. If you have any ideas for new unit tests testing the PR in a different way, I can add them. But as I understand it right now, all supported combinations are supported. I'm happy with the PR right now as well. By the way, may I ask when are you planning to merge the `rm_capstone` branch with `master`?

**Comment by stevemk14ebr** [comment]
Awesome, merged! I'll merge to master once the vcpkg situation is cleaned up

**Comment by stevemk14ebr** [comment]
fyi: https://twitter.com/stevemk14ebr/status/1518621861692817409?s=20&t=lRj-SnaELsbTEuQuDQ4TmQ

**Comment by acidicoala** [comment]
Very cool stuff, kind of like the articles about Polyhook 1 & 2 you've written earlier, which were very helpful when I was learning about hooking implementation.

**Pull request merged**
