### PR TITLE
Fix #135

### LINKED ISSUE #135: The lib file `asmtk.lib` not install to folder `_install/lib`
RT

### PR DESCRIPTION
**Pull request by halx99**

### CODE REVIEW

**Comment by acidicoala** [comment]
The proposed fix is not a proper solution. The reason why _asmtk_ lib is missing from the install directory is because the _asmtk_ project as it stands right now does not support CMake's `install` command. I submitted a PR https://github.com/asmjit/asmtk/pull/26 to address this issue a month ago when working on `vcpkg` port. You can reference your issue in https://github.com/asmjit/asmtk/pull/26 to show maintainers that there are projects that would benefit from that PR.

**Comment by acidicoala** [comment]
When the asmtk project merges my pending PR, then this issue would be fixed. You can checkout my fork with a branch containing this fix for now to see if it solves your issue: https://github.com/acidicoala/PolyHook_2_0/tree/asmtk-upsteam-fix

<details><summary>Screenshot</summary>

image
</details>

**Comment by halx99** [comment]
It is works, thanks

**Comment by acidicoala** [comment]
@halx99, Keep in mind that this was **temporary** demo branch. When the issue gets resolved upstream in asmtk, and Polyhook gets updated with the latest asmtk commit, I will remove that temporary branch. Hence, don't keep references to it in production environment.

**Comment by halx99** [comment]
> @halx99, Keep in mind that this was **temporary** demo branch. When the issue gets resolved upstream in asmtk, and Polyhook gets updated with the latest asmtk commit, I will remove that temporary branch. Hence, don't keep references to it in production environment.

Got it, thanks

**Pull request closed without merging**
