### PR TITLE
functions moved to cpp

### PR DESCRIPTION
**Pull request by kalinowskitomasz**
various improvements for *nix systems
fixes in cmake make it build shared/static without hacks
test runner is separate build target
memprotector fo *nix
some other clean-up like removing unneeded templates, etc.

### CODE REVIEW

**Comment by kalinowskitomasz** [comment]
I found out that tests are failing

**Comment by stevemk14ebr** [comment]
If you want to re-open another pull request, one for each change, we can merge your changes in piece by piece (i bet many of your improvements are fine)

**Comment by kalinowskitomasz** [comment]
I’ll have to investigate why tests are failing. Merging was really complicated as some of the changes on master were in headers and mine were in cpp files so I guess I missed something. I’ll try to break it down

**Comment by stevemk14ebr** [comment]
I understand, it would make my life easier if the changes were each a seperate pull request. That way i can verify what's changing, and since we already know there's some issues i want to do that merge as piece-meal as possible.

I would suggest not moving the .h/.cpp stuff for now.

**Comment by kalinowskitomasz** [comment]
Sure, I know. I think moving stuff from headers to cpp would be good last step. Implementation in headers is causing lots of trouble in long run. Growing compile time, compatibility issues for library users, maitnaince problems and will make migration to modules harder in future

**Comment by kalinowskitomasz** [comment]
As for the cmake have a look at this thing:
https://cgold.readthedocs.io/en/latest/tutorials/libraries/static-shared.html

**Comment by stevemk14ebr** [comment]
Yes i agree, i wanted to move to modules eventually. I broke bigger classes into .h/.cpp pairs but i defintely was lazy and missed some, i agree with this change. I also like 99% of the cmake mods you did, i am mentioning the changes suhc as 

> option(FEATURE_PE "Implement all win pe hooking functionality" OFF)
that was previously set to ON. And all of the cases of removing virtual and = default i do not agree with. The vast majority is ok, i especially like that you even corrected my own styling in places with the m_ . But keep style changes to a minimum please unless it is obviously different from the rest of the project (such as m_)

**Comment by tkalinowskiIress** [comment]
With Cmake that was my mistake, I must have overlooked this.
I replaced virtual with override as this is not only style issue. Override prevents tricky bugs and should be used in all inheriting function. Virtual used together with override is redundant and is marked by all style checkers as warning

**Comment by stevemk14ebr** [comment]
Thanks for providing reasoning, i personally disagree with those style checkers but i don't want to throw errors for people who use those. I will accept that change.

**Pull request closed without merging**
