### PR TITLE
Build improvement (part 2)

### PR DESCRIPTION
**Pull request by Mixaill**
* force `capstone` and `zydis` compilation for tests
* move code with calls to `libcapstone` to `.cpp`
* move code with calls to `libzydis` to `.cpp`
* add ability to control library type of dependencies separately from polyhook.

----

It gives possibility to create the following configuration which generates only one dynamic library:
* `polyhook` : dynamic
* `capstone`: static
* `zydis`: static

which simplifies linking a lot.

In this case, Polyhook consumer should perform linking only to `polyhook`, without the direct dependency from `capstone`/`zydis`.

### CODE REVIEW

**Comment by stevemk14ebr** [comment]
This looks great other than additional unique_ptr for the zydis code. Please use an initializer list instead, or if that is not possible then convert to std::optional

**Comment by Mixaill** [comment]
@stevemk14ebr fixed

**Comment by stevemk14ebr** [comment]
Would you be able to provide an example command line of the suggested build settings?

**Comment by Mixaill** [comment]
So I use something like that (very simplified, real life example here: https://gitlab.com/xvm/xfw/xfw.native/-/commit/295030e307562355315195f682300a5adbfdec8a )

-----

### directory layout:
```
* <my_repo_root>
    * _build <-- cmake build files
    * _install  <-- cmake installation dir
    * depends
        * polyhook
    * src
```

### 1. Build PolyHook

1. generate polyhook project
```shell
cmake "./depends/polyhook" -B"./_build/polyhook" -DCMAKE_INSTALL_PREFIX="./_install/" -DPOLYHOOK_BUILD_SHARED_LIB=ON -DPOLYHOOK_FEATURE_INLINENTD=OFF
```

2. build polyhook project
```shell
cmake --build "./_build/polyhook" --config Release --target INSTALL
```

### 2. Build dependent project

0. create `src/CMakeLists.txt`

```cmake
#project header
cmake_minimum_required (VERSION 3.15)
project(myproject LANGUAGES C CXX)

#find dependencies
find_package(PolyHook_2 REQUIRED)

#set library with it sources
add_library(mylibrary SHARED "library.cpp")

#link with dependencies
#include directories will be resolved automatically
target_link_libraries(mylibrary PRIVATE PolyHook_2::PolyHook_2)

#install library
install(TARGETS mylibrary
    RUNTIME DESTINATION "bin"
    LIBRARY DESTINATION "lib"
    ARCHIVE DESTINATION "lib"
)
```

1. generate dependent project
```
cmake "./src/" -B"./_build/myproject" -DCMAKE_INSTALL_PREFIX="./_install/" -DCMAKE_PREFIX_PATH="./_install"
```

2. build dependent project
```
cmake --build "./_build/myproject" --config Release --target INSTALL
```

**Pull request merged**
